### ISSUE TITLE
API4 update not compatible.

### ISSUE THREAD

**Issue by DatGoose** [Tenrys/FATEAutoSync#1]
Hiya I wanted to start off by saying thanks first for this plugin, it has been a huge quality of life improvement for not just farming fates but joining eureka stuff and not having to remember to click the dumb button every time. 

October 8th the xivlauncher dev team deployed apiv4 and broke the plugin, I'm hoping that you'll continue to support the plugin but if not, my thanks still for this amazing quality of life improvement I got to experience the last 6 months.

**Comment by Tenrys** [comment]
I didn't think anyone other than me was using this, and since I haven't
needed it I wasn't going to look at it.

But you've given me a reason to now, so I will try to see if I can fix it
this weekend

**Comment by Tenrys** [comment]
That wasn't too hard.

https://github.com/Tenrys/FATEAutoSync/releases/tag/1.1.0.0
