### ISSUE TITLE
Dalamud API 5

### ISSUE THREAD

**Issue by SelfAfflicted** [Tenrys/FATEAutoSync#2]
Are you, by chance, planning to update this to the current version of Dalamud? It's quite a useful plugin, and miss using it for all the FATE grinding I've been doing for Endwalker.

**Comment by Tenrys** [comment]
You can technically still use it if you change the API level in the `.json` file or tell Dalamud to load all API levels, but I guess I should update it in here.

**Comment by SelfAfflicted** [comment]
Ah, okay, thought it'd require more work than merely modifying the json file, thank you.

**Comment by Tenrys** [comment]
Updated the latest release, hopefully that actually works..?

**Comment by seathasky** [comment]
Its not working with dev settings on for all apis.

**Comment by Tenrys** [comment]
Very strange, it works for me..

**Comment by seathasky** [comment]
![Screen_Shot_2022-04-01_at_6 17 36_PM](https://user-images.githubusercontent.com/17598024/161378582-08f66e67-e198-4f49-9c77-82565136e975.png)

**Comment by seathasky** [comment]
Ive also tried doing it manually from the site and no go.
